#!/bin/bash

ROOT="`dirname $(readlink -f $0)`/.."
RELEASEDASHARCH=$1
NAME=$2
DEVICE=$3
XPACKAGE=$4

BUILDER=$ROOT/builders/openwrt-imagebuilder-${RELEASEDASHARCH}.Linux-x86_64
TARGET=$ROOT/images
mkdir -p $TARGET

# cat $ROOT/packages/$NAME
PACKAGES="$(cat $ROOT/packages/$NAME | tr '\n' ' ' )"
echo $PACKAGES

echo Enterting $BUILDER
pushd $BUILDER

# make clean

#echo Building image for $NAME with following packages:
#echo =================================================
#echo make manifest PROFILE="$DEVICE" PACKAGES="$PACKAGES"
#make manifest PROFILE="$DEVICE" PACKAGES="$PACKAGES $XPACKAGE"

echo =================================================
echo Building image for $NAME
echo =================================================

echo Build starting...
echo make image PROFILE="$DEVICE" PACKAGES="$PACKAGES $XPACKAGE" BIN_DIR="$TARGET" EXTRA_IMAGE_NAME="-$NAME-"
make image PROFILE="$DEVICE" PACKAGES="$PACKAGES $XPACKAGE" BIN_DIR="$TARGET" EXTRA_IMAGE_NAME="-$NAME-"

popd

